/**
 * Application Error Codes
 */
module.exports = {
  // General Errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Document Errors
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_GENERATION_FAILED: 'DOCUMENT_GENERATION_FAILED',
  INVALID_DOCUMENT_TYPE: 'INVALID_DOCUMENT_TYPE',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_INVALID: 'TEMPLATE_INVALID',

  // Field Errors
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  FIELD_INVALID: 'FIELD_INVALID',
  FIELD_NOT_FOUND: 'FIELD_NOT_FOUND',

  // Signature Errors
  SIGNATURE_FAILED: 'SIGNATURE_FAILED',
  SIGNATURE_INVALID: 'SIGNATURE_INVALID',
  SIGNATURE_VERIFICATION_FAILED: 'SIGNATURE_VERIFICATION_FAILED',
  SIGNER_NOT_FOUND: 'SIGNER_NOT_FOUND',
  INSUFFICIENT_SIGNATURES: 'INSUFFICIENT_SIGNATURES',
  DUPLICATE_SIGNATURE: 'DUPLICATE_SIGNATURE',

  // File Errors
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Database Errors
  DATABASE_ERROR: 'DATABASE_ERROR',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
};
